### ISSUE TITLE
Rename env variable

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/ram-datapipeline#36]
Rename the `DB_URI` env variable to `DB_CONNECTION`. The latter is used on the backend, and using consistent naming will make the deployment process easier.

**Comment by danielfdsilva** [comment]
Doing this the opposite way. Renaming `DB_CONNECTION` to `DB_URI` so we just need to change the `ram-backend` repo

**Comment by olafveerman** [comment]
Not fixing here.
